<a href="https://colab.research.google.com/github/sgl13/Deep_Learning/blob/main/Tensors_and_Neural_network_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Deep Learning**

 subset of machine learning based on artificial neural networks with multiple layers (hence "deep"). It enables algorithms to automatically learn features and patterns directly from raw data—such as images, text, or audio—without requiring manual feature engineering.

**Tensors**

In [1]:
#what is a tensor?
#tensors are specialized data structures that are very similar to array's and matrics
#we use the tensors to encode the inputs and outputs of model
#these are similar to numpy's arrays
#tensors can run on GPU or other hardware accelrators.
#so tensor is a container for numerical data
#ex:- 1 number --> scalar
#     1d collection --> [1,2,3,4,5,6] --> vectors
#.    2d     ---> matrix
#.    tensors-->3d,4d,5d .............
# age = [25,30,35,40] --> vector
# Age      salary
# 25        30000
# 30        45000
# 35.       60000
#2d --> matrix
#for ex:- take image --> height*width*channel
 #                         224 * 224 * 3
 #for a batch images --> batch * height * width * channel --> 4d tensor

In [2]:
#there are 2 frame works to work with tensors
#1.pytorch
#2.tensorflow

pytorch installation /import pytorch

In [3]:
import torch
import numpy as np

In [4]:
#print the version of pytorch
print(torch.__version__)

#we use pytorch to
#create tensors
#perform mathematical operations
#caluclate gradient
#built neural network
#train deep learning

2.11.0+cu128


**Create tensors**

In [5]:
#scalar(no dimension)
x = torch.tensor(10)
print(x)
print(type(x))
print(x.ndim)

tensor(10)
<class 'torch.Tensor'>
0


In [6]:
#vectors
L = [10,20,30,40,50]
a = torch.tensor(L)
print(a)
print(type(x))
print(a.ndim)
print(a.shape)

tensor([10, 20, 30, 40, 50])
<class 'torch.Tensor'>
1
torch.Size([5])


In [7]:
#create a tensor by using the matrix
b = torch.tensor([[10,20,30],[40,50,60]])
print(b)
print(type(b))
print(b.ndim)
print(b.shape)
print(b.dtype)
print(b.numel())
print(b.itemsize)
print(b.size())

tensor([[10, 20, 30],
        [40, 50, 60]])
<class 'torch.Tensor'>
2
torch.Size([2, 3])
torch.int64
6
8
torch.Size([2, 3])


In [8]:
#Note :- for neural networks we work with floating point values
b = b.float()
print(b)

tensor([[10., 20., 30.],
        [40., 50., 60.]])


In [9]:
#weights + multiply + gradient(least loss function) + optimization so floating point tensors are commomly used for this point

**Tensor creation function**

In [10]:
c = torch.zeros(3,4)
print(c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
#create tensors of ones with 2 rows and 3 columns
d = torch.ones(2,3)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [12]:
#create random tensors
e = torch.rand(3,3)
print(e)

tensor([[0.6821, 0.5721, 0.2358],
        [0.6580, 0.0832, 0.2091],
        [0.4552, 0.9758, 0.2947]])


In [13]:
#create random numbers with normal distributed data
n = torch.randn(3,3)
print(n)

tensor([[ 0.3801,  2.0485,  0.1923],
        [-1.8719,  0.9103, -0.0896],
        [-1.5569, -1.4216, -1.5054]])


In [14]:
#generate a range of tensors
r = torch.arange(5)
print(r)

tensor([0, 1, 2, 3, 4])


**Matrix multiplication**

In [15]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
c = torch.matmul(a,b)
print(c)

tensor([[19, 22],
        [43, 50]])


**reshape of an tensor**

In [16]:
c = torch.arange(12)
print(c)
#reshape it in to 3 rows and 4 columns
print(c.reshape(3,4))


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [17]:
#create a tensor  from numpy array
a = np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [18]:
tensor = torch.from_numpy(a)
print(tensor)

tensor([[10, 20],
        [30, 40]])


In [19]:
a = tensor.numpy()
print(a)

[[10 20]
 [30 40]]


In [20]:
#check the GPU's
print(torch.cuda.is_available())
#we need to enable the gpu's

True


In [21]:
#move a tensor to gpu
x = torch.tensor([1,2,3]).float()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") #ternary operators
x = x.to(device)
print(x.device)

cuda:0


In [22]:
#LLM --> millions/billions of parameters --> matrix multiplications --> GPU --> tensor caluclation

In [23]:
#pytorch automatically caluclate derivatives
x = torch.tensor(3.0,requires_grad=True)
y = x**2
print(y)

tensor(9., grad_fn=<PowBackward0>)


In [24]:
y.backward()
print(x.grad)
#the above execution is the function for backward propogations

tensor(6.)


**Neural Networks contains** --> input layer --> hidden layer --> output layer

In [25]:
#Age,Income,experiance --> purchase probability
#understanding the neurons
#A neuron can be perform like below
#z = x1w1 + x2w2 + x3w3 + b
#then an activation function is applied to above formula
#output = activation(z)
#relu,sigmoid,softmax

**predict wheather a customer will leave a company or not**

The above testcase relates to product base company so a DS needs to predicts who is going leave the company

In [26]:
#features --> age,tenure,monthly charges,support calls
#churn --> target(y)
#1 --> customer left
#0 --> customer stayed

**import the required libraries**

In [27]:
import pandas as pd #for datahandling
import numpy as np #numerical caluclation
import matplotlib.pyplot as plt #visualization
import tensorflow as tf

In [28]:
import torch
import torch.nn as nn
import torch.optim as optim #used for optimization and weight updates also reduce loss function

In [29]:
#check the weather GPU is available or not
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device",device)

Device cuda


In [30]:
url = "https://raw.githubusercontent.com/Nas-virat/Telco-Customer-Churn/master/Telco-Customer-Churn.csv"
df = pd.read_csv(url)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes


In [31]:
#q) what is each row represent in above data ?
#each customer details
#q) what are we trying to predict?
#churn
#q)which columns shouldnot be used a predictive features?
#customer id :

In [32]:
df.shape

(7043, 21)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [34]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges
count,7043.000000,7043.000000,7043.000000
mean,0.162147,32.371149,64.761692
std,0.368612,24.559481,30.090047
min,0.000000,0.000000,18.250000
25%,0.000000,9.000000,35.500000
50%,0.000000,29.000000,70.350000
75%,0.000000,55.000000,89.850000
max,1.000000,72.000000,118.750000


In [35]:
df.isnull().sum()

,0
customerID,0
gender,0
SeniorCitizen,0
Partner,0
Dependents,0
tenure,0
PhoneService,0
MultipleLines,0
InternetService,0
OnlineSecurity,0


In [36]:
#check the distribution of churn
df['Churn'].value_counts()

,count
Churn,
No,5174
Yes,1869


In [37]:
df.dtypes

,0
customerID,object
gender,object
SeniorCitizen,int64
Partner,object
Dependents,object
tenure,int64
PhoneService,object
MultipleLines,object
InternetService,object
OnlineSecurity,object


In [38]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors="coerce")

In [39]:
df['TotalCharges'].isnull().sum()

np.int64(11)

In [40]:
#these are very less values and compare the values with other rows
df[df['TotalCharges'].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No


In [41]:
df = df.dropna()

In [42]:
df.shape

(7032, 21)

In [43]:
df['Churn']
#convert the yes in to 1 and no in to 0

,Churn
0,No
1,No
2,Yes
3,No
4,Yes
...,...
7038,No
7039,No
7040,No
7041,Yes


In [44]:
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

In [45]:
df['Churn']

,Churn
0,0
1,0
2,1
3,0
4,1
...,...
7038,0
7039,0
7040,0
7041,1


In [46]:
#remove the customer ID
df = df.drop("customerID",axis=1)

In [47]:
#define feature and target
X = df.drop('Churn',axis=1)
y = df['Churn']

**Categorical variables**

In [48]:
#gender,partner,dependents,Internetservice,contract,paymentmethod
#encode the data because NN and ML cannot process the categorical data
#there is no order in my data we do one hot encoding
#in pandas to do one hot encoding we use the method --> pd.get_dummies
X = pd.get_dummies(X,drop_first=True)

In [49]:
X.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False


**Train test split**

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

**Scale the data**

In [51]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**To apply the neural networks convert the data in to tensors**

In [52]:
import torch
X_train_tensor = torch.tensor(X_train,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values,dtype=torch.float32).reshape(-1,1) # convert the y 1d to 2d
y_test_tensor = torch.tensor(y_test.values,dtype=torch.float32).reshape(-1,1)

In [53]:
print(X_train_tensor.shape)

torch.Size([5625, 30])


In [54]:
input_features = X_train_tensor.shape[1]
print(input_features)

30


**Build the neural network**

In [55]:
import torch.nn as nn
class ChurnModel(nn.Module):
    def __init__(self,input_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_features,32),
            nn.ReLU(),
            nn.Linear(32,16),
            nn.ReLU(),
            nn.Linear(16,1),
            nn.Sigmoid()
            )
    def forward(self,x):
      return self.network(x)

**Create the model**

In [56]:
model = ChurnModel(input_features)
print(model)

ChurnModel(
  (network): Sequential(
    (0): Linear(in_features=30, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=16, bias=True)
    (3): ReLU()
    (4): Linear(in_features=16, out_features=1, bias=True)
    (5): Sigmoid()
  )
)


**Caluclate the loss**

In [57]:
criterion = nn.BCELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)


In [58]:
epochs = 100
loss_hist = []
for epoch in range(epochs):
  #forward pass
  predictions = model(X_train_tensor)
  #calculate the loss
  loss = criterion(predictions,y_train_tensor)
  #gradient
  optimizer.zero_grad()
  #backpropogation
  loss.backward()
  #update weights
  optimizer.step()

  loss_hist.append(loss.item())

  if (epoch + 1)%10 == 0:
    print(
        f"epoch [({epoch+1}/{epochs})]"
        f"loss: {loss.item():.4f}"
    )

epoch [(10/100)]loss: 0.6414
epoch [(20/100)]loss: 0.6152
epoch [(30/100)]loss: 0.5824
epoch [(40/100)]loss: 0.5426
epoch [(50/100)]loss: 0.5032
epoch [(60/100)]loss: 0.4758
epoch [(70/100)]loss: 0.4615
epoch [(80/100)]loss: 0.4536
epoch [(90/100)]loss: 0.4484
epoch [(100/100)]loss: 0.4442
